### ISSUE TITLE
Docker Hub image is not up to date

### ISSUE THREAD

**Issue by pataquets** [simkim/tcpdam#9]
I've had problems running tcpdam from DH (https://hub.docker.com/r/simkim/tcpdam). Neither ```-c``` nor ```-ctrl-socket``` options were working. I've checked and looks like the DH image is outdated.
As of now, I've set up an automated build at https://hub.docker.com/r/pataquets/tcpdam , but looks like an update to the official image build is due :)
And while we're at it, I would like to ask you to set up an [automated build](https://docs.docker.com/docker-hub/builds/) from source, which would give the image more trust, since the build's source code is linked to a public repo.

Thank you for sharing this useful software.

**Comment by simkim** [comment]
Thanks @pataquets . I've setup the automated build based  on yours. The image is bigger and run as root  but it's now trusted. The previous Dockerfile has been moved to Dockerfile.run (to build locally and run in a small non root container)
